-- 코드를 입력하세요
WITH tb AS (
    SELECT 
        CATEGORY, 
        MAX(PRICE) as  MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
    ORDER BY MAX_PRICE DESC
)
, tb2 AS (
    SELECT CATEGORY, PRICE as MAX_PRICE, PRODUCT_NAME FROM FOOD_PRODUCT
)
    
SELECT CATEGORY, MAX_PRICE, PRODUCT_NAME 
FROM tb LEFT JOIN tb2 USING (CATEGORY,MAX_PRICE)