-- 코드를 입력하세요
SELECT
    TITLE,
    BOARD_ID,
    REPLY_ID,
    r.WRITER_ID,
    r.CONTENTS,
    DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD as b
JOIN USED_GOODS_REPLY as r
USING(BOARD_ID)
WHERE DATE_FORMAT(b.CREATED_DATE,'%Y-%m') = '2022-10'
ORDER BY r.CREATED_DATE, b.TITLE